# Generated by Django 4.1.2 on 2022-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.EmailField(max_length=64)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
