# Generated by Django 4.1.2 on 2022-10-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftCardApi', '0002_giftcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='user',
        ),
    ]
